coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "**/*_test.go"
  - "**/testdata/**"
  - "**/vendor/**"
  - "internal/**/test_utilities.go"
  - "internal/handlers/handler_test_suite.go"
  - "tools/**"
  - "internal/ui/common.go"
  - "internal/ui/palette.go"
  - "internal/ui/logo.go"

